services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dev_blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d dev_blog" ]
      interval: 5s
      timeout: 5s
      retries: 5
  articles:
    build:
      context: .
      dockerfile: cmd/articles/Dockerfile
    environment:
      - ARTICLES_CONFIG_PATH=./configs/articles.yaml
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
volumes:
  postgres_data: